
name: Release tagged build

on:
  workflow_call:
    secrets:
      MAVEN_DEPLOY_USER:
        required: false
      MAVEN_DEPLOY_PASSWORD:
        required: false
      CURSEFORGE_TOKEN:
        required: false
      MODRINTH_TOKEN:
        required: false
    inputs:
      workspace:
        description: 'setupCIWorkspace/setupDecompWorkspace'
        required: false
        default: "setupCIWorkspace"
        type: string
      zig-version:
        description: 'The zig version to use (if using GradleZigBuild)'
        required: false
        default: "__NONE__"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          echo "FPGradle and CI needs to be updated, CurseForge publishing was broken."
          exit 1